services:
  postfix-tlspol:
    image: zuplu/postfix-tlspol
    container_name: postfix-tlspol
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
      args:
        TARGETPLATFORM: ${TARGETPLATFORM:-}
        GITHUB_ACTIONS: ${GITHUB_ACTIONS:-}
        VERSION: ${VERSION:-undefined}
    ports:
      - "127.0.0.1:8642:8642"
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - postfix-tlspol-data:/data

volumes:
  postfix-tlspol-data:
