version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "07:00"
    commit-message:
      prefix: "chore(deps)"
    cooldown:
      default-days: 1
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /deployments
    schedule:
      interval: daily
      time: "07:00"
    cooldown:
      default-days: 1
    commit-message:
      prefix: "build(docker)"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "07:00"
    cooldown:
      default-days: 7
      semver-minor-days: 3
      semver-patch-days: 1
    allow:
      - dependency-type: all
    commit-message:
      prefix: "build(deps)"
    groups:
      golang-x:
        patterns:
          - "golang.org/x/*"
