server:

  address: 127.0.0.1:8642   # server:port to listen as a socketmap server

  tlsrpt: no                # set yes to enable Postfix 3.10+ TLSRPT support
                            # this is experimental, not backwards compatible
                            # and may result in delivery failures (default no)


dns:

  address: 127.0.0.53:53    # must support dnssec


redis:

  address: 127.0.0.1:6379   # redis compatible server:port to act as a cache

  db: 2                     # select redis db number

