services:
  postfix-tlspol:
    image: zuplu/postfix-tlspol
    container_name: postfix-tlspol
    build:
      context: ..
      dockerfile: ./utils/Dockerfile
    ports:
      - "127.0.0.1:8642:8642"
    restart: unless-stopped
    network_mode: bridge
