server:
  # server:port to listen as a socketmap server
  # or unix:/run/postfix-tlspol/tlspol.sock for Unix Domain Socket
  address: 127.0.0.1:8642

  # socket file permissions if Unix Domain Sockets are used (default 0666)
  socket-permissions: 0666

  # DEPRECATED: use QUERYwithTLSRPT instead of QUERY in Postfix main.cf
  # to enable Postfix 3.10+ TLSRPT support
  # setting this to true with reply with TLSRPT to both commands
  tlsrpt: false

  # prefetch when TTL is about to expire (default true)
  prefetch: true

  # cache file (default /var/lib/postfix-tlspol/cache.db)
  cache-file: /var/lib/postfix-tlspol/cache.db

dns:
  # must support DNSSEC
  address: 127.0.0.53:53