# Made with ❤️ by Zuplu.
# All rights reserved.

name: 🚀 Build and Deploy Docker Images

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  REGISTRY_IMAGE: "zuplu/postfix-tlspol"

permissions: read-all

jobs:
  test:
    name: 🧪 Unit Testing
    uses: ./.github/workflows/go-test.yaml

  metadata:
    name: 📊 Synthesize Docker Metadata
    runs-on: ubuntu-latest
    outputs:
      version: ${{ toJSON(steps.metadata.outputs.version) }}
      tags: ${{ toJSON(steps.metadata.outputs.tags) }}
      labels: ${{ toJSON(steps.metadata.outputs.labels) }}
      annotations: ${{ toJSON(steps.metadata.outputs.annotations) }}
      json: ${{ toJSON(steps.metadata.outputs.json) }}
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: ✨ Detect Version Tag
        run: |
          VERSION="$(git describe --tags --abbrev=0 --match 'v*')"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          BRANCH="$(git branch --show-current)"
          IS_LATEST="false"
          if [ "$BRANCH" = "main" ]; then
            NEW_COMMITS="$(git rev-list HEAD...@{upstream} --count)"
            if [ "$NEW_COMMITS" -eq 0 ]; then
              IS_LATEST="true"
            fi
          fi
          echo "IS_LATEST=$IS_LATEST" >> "$GITHUB_ENV"

      - id: metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # pin@v6.0.0
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        with:
          context: git
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=semver,pattern=v{{version}},value=${{ env.VERSION }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ env.VERSION }}
            type=semver,pattern=v{{major}},value=${{ env.VERSION }}
            type=raw,value=latest,enable=${{ env.IS_LATEST }}

  build:
    name: 🚧 Build Docker Images
    needs: [test, metadata]
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/amd64/v2
          - linux/amd64/v3
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
          - linux/386
          - linux/ppc64le
          - linux/riscv64
          - linux/s390x
    runs-on: ubuntu-latest
    steps:
      - name: 📑 Prepare environment
        run: |
          PLATFORM="$(echo "${{ matrix.platform }}" | tr '/' '-')"
          echo "PLATFORM=$PLATFORM" >> "$GITHUB_ENV"

      - name: 📦 Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v4

      - name: ⚙️ Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # pin@v4.0.0

      - name: 🛠️ Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # pin@v4.0.0

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # pin@v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🏗️ Build platform-specific Docker image 🚧
        id: build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # pin@v7.0.0
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          platforms: ${{ matrix.platform }}
          build-args: |
            GITHUB_ACTIONS=1
            VERSION=${{ fromJSON(fromJSON(needs.metadata.outputs.json)).labels['org.opencontainers.image.version'] }}
          context: .
          file: deployments/Dockerfile
          push: true
          sbom: true
          provenance: true
          labels: ${{ fromJSON(needs.metadata.outputs.labels) }}
          annotations: ${{ fromJSON(needs.metadata.outputs.annotations) }}
          outputs: type=image,"name=${{ env.REGISTRY_IMAGE }}",push-by-digest=true,name-canonical=true,push=true
          cache-to: type=gha,mode=max,scope=${{ env.PLATFORM }}
          cache-from: type=gha,scope=${{ env.PLATFORM }}

      - name: 📄 Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: 📤 Upload digest
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # pin@v4
        with:
          name: digest-${{ env.PLATFORM }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  bundle:
    name: 📦 Bundle and Deploy ✨
    needs: [metadata, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    env:
      METADATA: ${{ fromJSON(needs.metadata.outputs.json) }}
    steps:
      - name: 📥 Download digests
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # pin@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-*
          merge-multiple: true

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # pin@v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ✨ Bundle and push manifest
        working-directory: ${{ runner.temp }}/digests
        run: |
          DIGEST="$(docker buildx imagetools create --progress rawjson \
            $(jq -r '.tags | map("-t \(.)") | join(" ")' <<< "$METADATA") \
            $(printf "${{ env.REGISTRY_IMAGE }}@sha256:%s " *) 2>&1 | \
            jq -r 'select(has("logs")) | .logs[].data | @base64d | match("sha256:[a-f0-9]{64}").string' | tail -n1)"
          echo "DIGEST=$DIGEST" >> "$GITHUB_ENV"

      - name: 🔏 Attest build provenance
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # pin@v4
        id: attest
        with:
          subject-name: docker.io/${{ env.REGISTRY_IMAGE }}
          subject-digest: ${{ env.DIGEST }}
          push-to-registry: true
