# Made with ❤️ by Zuplu.
# All rights reserved.

name: 🧪 Run unit tests

on:
  push:
    paths: "**/*.go"
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: 🕵🏻‍♂️ Analyze Compiling, DANE and MTA-STS Lookup
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: ⚙️ Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
        with:
          go-version-file: ./go.mod
      - name: 🧐 Test basic functionality
        run: go test -v -count=1 -failfast -tags netgo ./...
